-- begin REPORTGENERATION_ORDER_ITEM
alter table REPORTGENERATION_ORDER_ITEM add constraint FK_REPORTGENERATION_ORDER_ITEM_PRODUCT foreign key (PRODUCT_ID) references REPORTGENERATION_PRODUCT(ID)^
alter table REPORTGENERATION_ORDER_ITEM add constraint FK_REPORTGENERATION_ORDER_ITEM_ORDER foreign key (ORDER_ID) references REPORTGENERATION_ORDER(ID)^
create index IDX_REPORTGENERATION_ORDER_ITEM_ORDER on REPORTGENERATION_ORDER_ITEM (ORDER_ID)^
create index IDX_REPORTGENERATION_ORDER_ITEM_PRODUCT on REPORTGENERATION_ORDER_ITEM (PRODUCT_ID)^
-- end REPORTGENERATION_ORDER_ITEM
-- begin REPORTGENERATION_ORDER
alter table REPORTGENERATION_ORDER add constraint FK_REPORTGENERATION_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references REPORTGENERATION_CUSTOMER(ID)^
create index IDX_REPORTGENERATION_ORDER_CUSTOMER on REPORTGENERATION_ORDER (CUSTOMER_ID)^
-- end REPORTGENERATION_ORDER
-- begin REPORTGENERATION_CUSTOMER
alter table REPORTGENERATION_CUSTOMER add constraint FK_REPORTGENERATION_CUSTOMER_LOGO foreign key (LOGO_ID) references SYS_FILE(ID)^
create index IDX_REPORTGENERATION_CUSTOMER_LOGO on REPORTGENERATION_CUSTOMER (LOGO_ID)^
-- end REPORTGENERATION_CUSTOMER
