alter table REPORTGENERATION_CUSTOMER add constraint FK_REPORTGENERATION_CUSTOMER_LOGO foreign key (LOGO_ID) references SYS_FILE(ID);
create index IDX_REPORTGENERATION_CUSTOMER_LOGO on REPORTGENERATION_CUSTOMER (LOGO_ID);
